export const ROLE_DICTIONARY = {
  'questions.role': 'Perfil',
  'courses.course': 'Curso',
  'questions.question': 'Questão',
  'questions.axis': 'Eixo de Formação',
  'sessions.session': 'Sessão ?',
  'auth.permission': 'Permissão',
  'auth.group': 'Grupo',
  'questions.questiontype': 'Tipo de Questão',
  'questions.category': 'Categoria',
  'authtoken.tokenproxy': 'Token Proxy',
  'questions.subject': 'Assunto',
  'users.user': 'Usuário',
  'authtoken.token': 'Token de Autenticação',
  'contenttypes.contenttype': 'Tipo de Conteúdo',
  'questions.reviewrequest': 'Revisão de Questão',
  'questions.reviewmessage': 'Mensagem de Revisão',
  'admin.logentry': 'Log de Administração',
};
